# Generated by Django 6.0.1 on 2026-01-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_grade_assignment_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='grade',
            field=models.CharField(default='10', max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='section',
            field=models.CharField(default='A', max_length=50),
        ),
    ]
