# Generated by Django 6.0.1 on 2026-01-20 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('core', '0001_initial'),
        ('hr', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_published', models.BooleanField(default=False, help_text='If True, results are visible to parents')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.exambatch')),
            ],
            options={
                'unique_together': {('batch', 'classroom', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='GradeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_label', models.CharField(help_text='A, B, C, etc.', max_length=5)),
                ('grade_point', models.DecimalField(decimal_places=2, help_text='4.0, 3.7 etc.', max_digits=4)),
                ('grade_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='exams.gradescale')),
            ],
            options={
                'ordering': ['-min_score'],
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_absent', models.BooleanField(default=False)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student')),
            ],
            options={
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
