# Generated by Django 6.0.1 on 2026-01-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('grade_letter', models.CharField(max_length=5)),
                ('label', models.CharField(max_length=50)),
                ('color_code', models.CharField(default='text-green-400', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='markentry',
            name='score',
        ),
        migrations.RemoveField(
            model_name='markentry',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='markentry',
            name='is_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='markentry',
            name='practical_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='markentry',
            name='theory_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='markentry',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
