# Generated by Django 6.0.1 on 2026-01-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Nexus Institute', max_length=200)),
                ('address', models.TextField(default='123 Education Lane')),
                ('contact_email', models.EmailField(default='admin@nexus.edu', max_length=254)),
                ('contact_phone', models.CharField(default='+1 234 567 890', max_length=20)),
            ],
        ),
    ]
