# Generated by Django 6.0.1 on 2026-01-22 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='message',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='is_pinned',
        ),
        migrations.AddField(
            model_name='notice',
            name='audience',
            field=models.CharField(choices=[('ALL', 'Everyone'), ('STUDENT', 'Students Only'), ('TEACHER', 'Teachers Only')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='posted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('ANNOUNCEMENT', 'General Announcement'), ('EVENT', 'Event'), ('HOLIDAY', 'Holiday'), ('URGENT', 'Urgent Alert')], default='ANNOUNCEMENT', max_length=20),
        ),
    ]
