# Generated by Django 6.0.1 on 2026-01-23 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused / Leave'), ('HALF_DAY', 'Half Day')], default='PRESENT', max_length=10)),
                ('remarks', models.CharField(blank=True, help_text='Reason for absence or late arrival', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('session_type', models.CharField(choices=[('MORNING', 'Morning Session'), ('AFTERNOON', 'Afternoon Session'), ('EXAM', 'Exam Attendance')], default='MORNING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'classroom'],
            },
        ),
    ]
