# Generated by Django 6.0.1 on 2026-01-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('purpose', models.TextField()),
                ('person_to_meet', models.CharField(max_length=100)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ON_CAMPUS', 'On Campus'), ('CHECKED_OUT', 'Checked Out')], default='ON_CAMPUS', max_length=20)),
            ],
        ),
    ]
