# Generated by Django 6.0.1 on 2026-01-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('ID_CARD', 'Student ID Card'), ('TRANSFER', 'Transfer Certificate (TC)'), ('CHARACTER', 'Character Certificate'), ('REPORT', 'Report Card')], max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('validation_code', models.CharField(editable=False, max_length=20, unique=True)),
            ],
        ),
    ]
