# Generated by Django 6.0.1 on 2026-01-23 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('batch', 'classroom', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='studentresult',
            unique_together={('exam', 'student')},
        ),
    ]
