"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path
from datetime import timedelta
# Import CSP Constants for the new v4.0 configuration
from csp.constants import NONCE, STRICT_DYNAMIC, SELF, UNSAFE_INLINE, UNSAFE_EVAL

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- 1. DEFINE PATH TO REACT BUILD ---
FRONTEND_DIST = BASE_DIR.parent / 'frontend' / 'dist'

# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-l3_&^p2@!12nq4s(fgwspt)*=5s@3@fqofva#o)uh6gf-avpmy'

DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django_filters',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third Party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'csp', # <--- REQUIRED for django-csp v4.0+

    # Local
    'core',
    'students',
    'finance',
    'academics',
    'attendance',
    'notices',
    'exams',
    'library',
    'assignments',
    'hr',
    'certificates',
    'visitors',
    'health',
    'timetable',
    'results',
    'transport',
]

MIDDLEWARE = [
    'csp.middleware.CSPMiddleware',              # <--- FIXED IMPORT PATH
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [FRONTEND_DIST],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --- STATIC FILES CONFIGURATION ---
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    FRONTEND_DIST,
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Auth Model
AUTH_USER_MODEL = 'core.User'

# --- CORS SETTINGS ---
CORS_ALLOW_ALL_ORIGINS = False 
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8000",
]

# --- DRF & JWT SETTINGS ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'core.authentication.CookieJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# --- CONTENT SECURITY POLICY (CSP) v4.0 CONFIGURATION ---
# We now use the 'CONTENT_SECURITY_POLICY' dictionary format.

CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        # Scripts: Allow 'nonce' (generated automatically), 'strict-dynamic', and standard protocols
        "script-src": [NONCE, STRICT_DYNAMIC, UNSAFE_INLINE, UNSAFE_EVAL, "http:", "https:"],
        
        # Styles: Allow self, unsafe-inline (needed for many UI libs), and Google Fonts
        "style-src": [SELF, UNSAFE_INLINE, "https://fonts.googleapis.com"],
        
        # Images: Allow self, data (base64), and https
        "img-src": [SELF, "data:", "https:"],
        
        # Fonts: Allow self, Google Fonts data
        "font-src": [SELF, "https://fonts.gstatic.com", "data:"],
        
        # Default fallback
        "default-src": [SELF],
    }
}