# Generated by Django 6.0.1 on 2026-01-23 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Mathematics, English Literature', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short Code e.g. MATH-101', max_length=20, unique=True)),
                ('subject_type', models.CharField(choices=[('THEORY', 'Theory'), ('PRACTICAL', 'Practical / Lab'), ('ELECTIVE', 'Elective (Optional)')], default='THEORY', max_length=20)),
                ('credits', models.PositiveIntegerField(default=1, help_text='Credit weightage for this subject')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_link', models.URLField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_subjects', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Subject Allocation',
                'verbose_name_plural': 'Subject Allocations',
                'unique_together': {('academic_year', 'classroom', 'subject')},
            },
        ),
    ]
