# Generated by Django 6.0.1 on 2026-01-20 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectallocation',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.classroom'),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_subjects', to='hr.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectallocation',
            unique_together={('academic_year', 'classroom', 'subject')},
        ),
    ]
