# Generated by Django 6.0.1 on 2026-01-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='pass_practical_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='pass_theory_marks',
            field=models.IntegerField(default=33),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_practical_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_theory_marks',
            field=models.IntegerField(default=100),
        ),
    ]
