# Generated by Django 6.0.1 on 2026-01-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('DRIVER', 'Driver'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='STAFF', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='academics.subject'),
        ),
    ]
